#! /bin/csh -f
goto getem2
#/scr/js1/vinson/chatlogs/G5.log.17Feb2006
# cp -ip /scr/js1/vinson/chatlogs/G5.log.18Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.20Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.21Feb2006 .
#/scr/js1/vinson/chatlogs/G5.log.22Feb2006
# cp -ip /scr/js1/vinson/chatlogs/G5.log.23Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.24Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.25Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.26Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.27Feb2006 .
#/scr/js1/vinson/chatlogs/G5.log.28Feb2006
#
#/scr/js1/vinson/chatlogs/G5.log.01Mar2006
#/scr/js1/vinson/chatlogs/G5.log.02Mar2006
#/scr/js1/vinson/chatlogs/G5.log.03Mar2006
#/scr/js1/vinson/chatlogs/G5.log.04Mar2006
#/scr/js1/vinson/chatlogs/G5.log.05Mar2006
#/scr/js1/vinson/chatlogs/G5.log.06Mar2006
#/scr/js1/vinson/chatlogs/G5.log.07Mar2006
#/scr/js1/vinson/chatlogs/G5.log.08Mar2006
#/scr/js1/vinson/chatlogs/G5.log.09Mar2006
# cp -ip /scr/js1/vinson/chatlogs/G5.log.10Mar2006 .
#/scr/js1/vinson/chatlogs/G5.log.11Mar2006
#/scr/js1/vinson/chatlogs/G5.log.12Mar2006
#/scr/js1/vinson/chatlogs/G5.log.13Mar2006
# cp -ip /scr/js1/vinson/chatlogs/G5.log.14Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.15Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.16Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.17Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.18Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.19Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.20Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.21Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.22Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.23Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.24Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.25Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.26Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.27Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.28Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.29Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.30Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.31Mar2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/G5.log.01Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.02Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.03Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.04Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.05Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.06Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.07Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.08Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.09Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.10Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.11Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.12Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.13Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.14Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.15Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.16Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.17Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.18Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.19Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.20Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.21Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.22Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.23Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.24Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.25Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.26Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.27Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/G5.log.28Apr2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/trex.log.03Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.05Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.07Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.08Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.09Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.10Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.12Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.13Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.14Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.15Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.16Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.17Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.18Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.20Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.21Feb2006 .
#/scr/js1/vinson/chatlogs/trex.log.22Feb2006
#/scr/js1/vinson/chatlogs/trex.log.23Feb2006
#/scr/js1/vinson/chatlogs/trex.log.24Feb2006
#/scr/js1/vinson/chatlogs/trex.log.25Feb2006
#/scr/js1/vinson/chatlogs/trex.log.26Feb2006
#/scr/js1/vinson/chatlogs/trex.log.27Feb2006
#/scr/js1/vinson/chatlogs/trex.log.28Feb2006
#
#/scr/js1/vinson/chatlogs/trex.log.01Mar2006
#/scr/js1/vinson/chatlogs/trex.log.02Mar2006
#/scr/js1/vinson/chatlogs/trex.log.03Mar2006
#/scr/js1/vinson/chatlogs/trex.log.04Mar2006
#/scr/js1/vinson/chatlogs/trex.log.05Mar2006
#/scr/js1/vinson/chatlogs/trex.log.06Mar2006
#/scr/js1/vinson/chatlogs/trex.log.07Mar2006
#/scr/js1/vinson/chatlogs/trex.log.08Mar2006
#/scr/js1/vinson/chatlogs/trex.log.09Mar2006
#/scr/js1/vinson/chatlogs/trex.log.10Mar2006
#/scr/js1/vinson/chatlogs/trex.log.11Mar2006
#/scr/js1/vinson/chatlogs/trex.log.12Mar2006
#/scr/js1/vinson/chatlogs/trex.log.13Mar2006
# cp -ip /scr/js1/vinson/chatlogs/trex.log.14Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.15Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.16Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.17Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.18Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.19Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.20Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.21Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.22Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.23Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.24Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.25Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.26Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.27Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.28Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.29Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.30Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.31Mar2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/trex.log.01Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.02Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.03Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.04Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.05Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.06Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.07Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.08Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.09Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.10Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.11Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.12Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.13Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.14Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.15Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.16Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.17Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.18Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.19Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.20Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.21Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.22Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.23Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.24Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.25Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.26Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.27Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/trex.log.28Apr2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.01Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.02Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.03Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.05Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.07Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.08Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.09Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.10Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.12Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.13Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.14Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.15Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.16Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.17Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.19Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.20Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.21Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.22Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.24Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.25Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.26Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.27Feb2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.28Feb2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.01Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.02Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.03Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.04Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.05Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.06Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.07Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.08Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.09Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.10Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.11Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.12Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.13Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.14Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.15Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.16Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.17Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.18Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.19Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.20Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.21Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.22Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.23Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.24Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.25Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.26Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.27Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.28Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.29Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.30Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.31Mar2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.01Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.02Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.03Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.04Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.05Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.06Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.07Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.08Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.09Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.10Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.11Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.12Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.13Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.14Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.15Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.16Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.17Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.18Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.19Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.20Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.21Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.23Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.24Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.25Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.26Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/dropsonde.log.27Apr2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.02Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.03Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.04Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.05Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.06Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.07Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.08Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.09Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.10Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.11Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.12Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.13Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.14Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.15Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.16Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.17Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.18Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.19Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.20Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.21Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.22Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.23Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.24Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.25Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.26Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.27Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.28Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.29Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.30Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.31Mar2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.01Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.02Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.03Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.04Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.05Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.06Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.07Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.08Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.09Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.10Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.11Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.13Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.14Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.15Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.16Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.17Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.18Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.19Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.20Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.21Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.23Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.24Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.25Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.26Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.27Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.28Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/bae146.log.29Apr2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.02Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.03Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.04Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.05Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.06Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.07Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.08Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.09Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.10Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.11Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.12Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.13Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.14Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.15Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.16Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.17Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.18Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.19Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.20Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.21Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.22Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.23Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.24Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.25Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.26Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.27Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.28Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.29Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.30Mar2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.31Mar2006 .
#
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.01Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.02Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.03Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.04Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.05Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.06Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.07Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.08Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.09Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.10Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.11Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.12Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.13Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.14Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.15Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.16Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.17Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.18Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.19Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.20Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.21Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.23Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.24Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.25Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.26Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.27Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.28Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.29Apr2006 .
# cp -ip /scr/js1/vinson/chatlogs/kingair.log.30Apr2006 .
exit
#
getem2:
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.01Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.02Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.03Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.04Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.05Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.06Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.07Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.08Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.09Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.11Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.12Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.13Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.17Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.22Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/G5.log.28Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.02Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.03Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.04Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.05Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.06Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.07Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.08Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.09Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.10Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.11Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.12Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/kingair.log.13Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.01Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.02Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.03Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.04Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.05Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.06Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.07Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.08Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.09Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.10Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.11Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.12Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.13Mar2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.22Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.23Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.24Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.25Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.26Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.27Feb2006 .
 \cp -ip /scr/js1/vinson/chatlogs/trex.log.28Feb2006 .
exit
