#!/bin/sh
#

Rscript -e "library(knitr); knitr::purl('/h/eol/janine/Rstudio/HeightOfTerrain/HeightOfTerrain.Rnw')"

project="ORCAS"
lt_s="-80"
lt_n="-30"
lg_w="-105"
lg_e="-30"
Tdb="no"

echo "Adding Terrain Ht vars to production netCDF files for project $project"
echo "Using lat/long range $lt_s - $lt_n, $lg_w - $lg_e"

for file in `ls /scr/raf/Prod_Data/${project}/${project}[rtf]f??.nc`
do
    flight=${file:(-7):4}
    Rscript ./HeightOfTerrain.R $project $flight $lt_s $lt_n $lg_w $lg_e $Tdb
done
