#!/bin/csh
# Britt has a script that calls all the proj dirs looking for netCDF files. It assumes they are
# in the top-level dir (not a version subdir) and that they don't have a Z in the title, so 
# this script meets that need for him.
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASff01Z.nc /scr/raf/Prod_Data/ORCAS/ORCASff01.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASff02Z.nc /scr/raf/Prod_Data/ORCAS/ORCASff02.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASff03Z.nc /scr/raf/Prod_Data/ORCAS/ORCASff03.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf01Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf01.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf02Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf02.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf03Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf03.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf04Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf04.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf05Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf05.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf06Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf06.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf07Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf07.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf08Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf08.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf09Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf09.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf10Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf10.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf11Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf11.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf13Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf13.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf14Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf14.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf15Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf15.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf16Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf16.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf17Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf17.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf18Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf18.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCASrf19Z.nc /scr/raf/Prod_Data/ORCAS/ORCASrf19.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCAStf01Z.nc /scr/raf/Prod_Data/ORCAS/ORCAStf01.nc
ln -s /scr/raf/Prod_Data/ORCAS/V1.1_20181015/ORCAStf02Z.nc /scr/raf/Prod_Data/ORCAS/ORCAStf02.nc
