#!/bin/csh

set user = `whoami`
if ($user == 'nimbus') then
        cd /scr/raf/local_productiondata
else
        cd ${DATA_DIR}
endif

foreach file ( MPEX_?f??.nc )
  echo $file
  ncReorder $file temp_mpex.nc
  mv -f temp_mpex.nc $file
  chmod g+w $file
end
