#!/bin/csh

foreach FILENAME (setup_rf??)
/code/schanot/nimbus/src/filter/nimbus -b $FILENAME << EOF
Y
EOF
end

cd /jnet/productiondata/
foreach FILENAME (STARTrf??.nc)
ncReorder $FILENAME temp.nc
mv -f temp.nc $FILENAME
end

