#!/bin/sh
#
#	/etc/rc.d/init.d/udp2sql
#
#	Startup script for udp2sql
#
# chkconfig: 2345 95 05
# description: Read UDP packets from the aircraft and write.
# pidfile: /var/run/udp2sql.pid
#
# Note:
#   This is killed before, and started after the 'network' script.

# Source function library.
. /etc/init.d/functions

prog=udp2sql

# User to run udp2sql as
user="root"

# This is where the log will go
logfile="/var/log/$prog.log"

# Start command.
cmd="/usr/local/bin/$prog < /dev/null >>$logfile 2>&1 &"

start() {
	# Move the previous logfile, if any
	if [[ -e $logfile ]]; then
		mv $logfile $logfile.old
	fi
	action $"Starting $prog:" su $user -c "$cmd"
}

stop() {
        echo -n $"Shutting down $prog: "
        killproc $prog
        echo
}

case "$1" in
    start|restart)
	stop
	start
	;;
    stop)
	stop
	;;
    *)
	echo $"Usage: $prog {start|stop|restart}"
	exit 1
	;;
esac
exit $?
