#!/bin/sh
#
# Start udp2sql to read UDP packets from the aircraft and write
# the data to the database
#

# User to run udp2sql as
user="ads"

# This is where the log will go
logfile="/tmp/udp2sql.log"

# Move the previous logfile, if any
if [[ -e $logfile ]]; then
        mv $logfile $logfile.old
fi

# Start the new udp2sql in background, logging to $logfile.  Assume that udp2sql
# lives in the same place as this script.
homedir=/home/$user/udp2sql

# Start command.
cmd="$homedir/udp2sql < /dev/null >$logfile 2>&1 &"

case "$1" in
  start)
    $0 stop
    su $user -c "$cmd"
    ;;
  stop)
    killall udp2sql
    ;;
  restart)
    $0 stop
    su $user -c "$cmd"
    ;;
  *)
    echo $"Usage: rt_db {start|stop|restart}"
    exit 1
esac

exit 0

