#!/bin/csh

#cd /scr/raf/local_data
cd /scr/raf/local_productiondata
ncmerge -v GGLAT,GGLON,ALTX HIPPO-3rf03.nc /jnet/local/projects/HIPPO-3/GV_N677F/Production/Position_Interpolation/HIPPO3_posint_rf03.nc
ncmerge -v GGLAT,GGLON,ALTX HIPPO-3rf06.nc /jnet/local/projects/HIPPO-3/GV_N677F/Production/Position_Interpolation/HIPPO3_posint_rf06.nc
ncmerge -v GGLAT,GGLON,ALTX HIPPO-3rf10.nc /jnet/local/projects/HIPPO-3/GV_N677F/Production/Position_Interpolation/HIPPO3_posint_rf10.nc
ncmerge -v GGLAT_GMN,GGLON_GMN,ALTX HIPPO-3rf04.nc /jnet/local/projects/HIPPO-3/GV_N677F/Production/Position_Interpolation/HIPPO3_posint_rf04.nc
