#!/bin/bash
#
# /etc/init.d/viper_dio
#       Starts viper_dio driver module and creates the device files.
#
# chkconfig: 2345 50 75
# description: Insert a driver module for the viper digital IO lines.
#		Create devices.
#

# set -x

RETVAL=0

# PATH=/usr/local/bin:$PATH

tmpdir=/var/tmp/dev

clear_tmpdevs() {
    [ -d $tmpdir ] || mkdir -p $tmpdir
    rm -f $tmpdir/viper_dio*
}

create_devs() {
    modprobe viper_dio

    dev=viper_dio0
    emajor=`cat /proc/devices | fgrep viper_dio | cut -d\  -f1`
    eminor=0

    # viper_dio major number may change from boot to boot
    # so we create the device file on $tmpdir
    # and create a link to it from /dev.
    rm -f $tmpdir/$dev
    [ -c $tmpdir/$dev ] || mknod $tmpdir/$dev c $emajor $eminor
    chmod 666 $tmpdir/$dev
    [ -h /dev/$dev ] || ln -s $tmpdir/$dev /dev
}


case "$1" in
    start)
	clear_tmpdevs
        create_devs
	;;
    stop)
	rmmod viper_dio
	;;
    *)
	echo "usage: $0 start|stop"
	RETVAL=1
	;;
esac
exit $RETVAL

