#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac :9 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :9.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/ARISTO2017
endif

mkdir ${DAT}

nice ./run_nimbus_hrt
nice ./reorder_all_hrt
#nice ./run_proc2d_hrt

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
