# -*- python -*-

env = Environment(tools = ["default", "qt"])

env.AppendUnique(LIBS = ["ssl", "pq", "bz2", "crypto"])

SOURCES = Split("""
main.cc
udp2sql.cc
""")

HEADERS = Split("""
udp2sql.h
""")

env.Program("udp2sql", SOURCES)

