# -*- python -*-

env = Environment(tools = ["default", "qt4", "nidas"])

env.Append(CXXFLAGS='-g -Werror -I/usr/include/python2.4/')
env.EnableQt4Modules(['QtNetwork'])
env.AppendUnique(LIBS = ["ssl", "pq", "bz2", "crypto", "python2.4", "nidas_util"])

SOURCES = Split("""
main.cc
udp2sql.cc
""")

HEADERS = Split("""
udp2sql.h
""")

app = env.Program('udp2sql', SOURCES)

EXECPATH = env.get('UDP2SQL_INSTALL_PATH', '/opt/local/bin/')

env.Install(EXECPATH, app)

env.Alias('install', EXECPATH)
