# -*- python -*-

env = Environment(tools = ["default", "qt4", "nidas"])

env.EnableQt4Modules(['QtNetwork'])
env.AppendUnique(LIBS = ["ssl", "pq", "bz2", "crypto", "nidas_util"])

SOURCES = Split("""
main.cc
udp2sql.cc
""")

HEADERS = Split("""
udp2sql.h
""")

app = env.Program('udp2sql', SOURCES)

EXECPATH = '/opt/local/bin/'

env.Install(EXECPATH, app)

env.Alias('install', EXECPATH)
