######################################################################
# Automatically generated by qmake (1.04a) Sun Jan 4 14:46:13 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += udp2sql.h
SOURCES += main.cc udp2sql.cc
LIBS += -lpq
