#!/bin/csh

#/usr/X11R6/bin/Xvfb :3 -ac -screen 1 1024x768x16 &
#setenv DISPLAY :3.1

#Following line not needed; PMSspecs is correct:
#/bin/cp -f ../PMSspecs.rev1 ../PMSspecs
/bin/cp -f ../Lags.lrt ../Lags
/bin/cp -f ../s109.default_extended_range ../s109.default

nice nimbus -b setup_tf01
nice nimbus -b setup_tf02
nice nimbus -b setup_tf03
nice nimbus -b setup_rf01
nice nimbus -b setup_rf02
nice nimbus -b setup_rf03
nice nimbus -b setup_rf04

# Extended range cards were removed, now use standard:
/bin/cp -f ../s109.default_standard_range ../s109.default
nice nimbus -b setup_rf05
nice nimbus -b setup_rf06
nice nimbus -b setup_rf07

#Following line not needed; PMSspecs is correct:
#/bin/cp -f ../PMSspecs.rev2 ../PMSspecs

nice nimbus -b setup_rf08
nice nimbus -b setup_rf09
nice nimbus -b setup_rf10
nice nimbus -b setup_rf11
nice nimbus -b setup_rf12
nice nimbus -b setup_tf04

# Remove Xvfb
#kill %1

cd /jnet/productiondata/
rm ice_temp.nc
foreach FILENAME (ICE-L*.nc)
ncReorder $FILENAME ice_temp.nc
if (-e ice_temp.nc) then
  mv -f ice_temp.nc $FILENAME
endif
end

