#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac :2 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :2.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/ARISTO
endif

mkdir ${DAT}

nice ./run_nimbus
nice ./reorder_all

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
