#!/bin/bash

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :2 &
xvpid=$!
trap "kill $xvpid; exit 1" SIGINT SIGTERM
sleep 2

DISPLAY=:2.1

source ./set_env
source ${PROJ_DIR}/scripts/production_fns.sh
initialize_processing

./run_nimbus
./run_nimbus_hrt
./run_nimbus_srt # Requested by Sarah Woods for in-house work

# reorder_all changes the current working dir. Save it so can
# come back
CWD=$PWD
source ${PROJ_DIR}/scripts/reorder_all $PROJ
cd $CWD

#./run_proc2d - not requested for INSPYRE

./run_iwg

# Before uncommenting run_icartt, be sure nc2asc.bat is updated with the
# latest revision info
./run_icartt

#source ${PROJ_DIR}/scripts/AddHtTerrain $PROJ

if [ `whoami` == nimbus ]; then
#  run_kalmanFilter
  true
fi

# Recreate QAtools output
#./run_QAtools

cleanup_processing

kill $xvpid
exit 0
