#!/bin/bash

source ./set_env

# BEFORE RUNNING THIS SCRIPT, MANUALLY UPDATE /opt/local/bin/nc2asc as
# appropriate for new version and set version indicator letter here:
version="E"

# Remove existing files.  Helps to avoid residual data if nc2asc fails
/bin/rm ${DAT}/${PROJ}-CORE_GV_????????_R${version}*.ict

for file in ${DAT}/${PROJ}?f??.nc
do
  takeoff=`flt_time ${file} | sed -n 's/^Takeoff: //p'`
  ymd=`date -d "$takeoff" +%Y%m%d`
  outfile="${DAT}/${PROJ}-CORE_GV_${ymd}_R${version}"
  if [[ -f "$outfile.ict" ]]; then
    # If recreating an existing file, assume have two legs.
    # Code does NOT handle more than two legs ATM.
    base=${outfile%.ict}
    newoutfile=${base}_L1.ict
    mv $outfile $newoutfile
    nc2asc -i $file -o $outfile -b ../scripts/nc2asc.bat
    base=${outfile%.ict}
    newoutfile=${base}_L2.ict
    mv $outfile $newoutfile
  else
    echo "nc2asc -i $file -o $outfile.ict -b ../scripts/nc2asc.bat"
    exit
  fi
done
