#!/bin/bash
# Run this script if everything is reprocessed on the groundstation and you 
# want to copy files to syncthing so they can be uploaded to field.eol.ucar.edu
cd /home/data/INSPYRE
cp INSPYRE?f??h.nc /var/r1/field_sync/EOL_Data/RAF_Data/HRT/.
cp INSPYRE?f??.nc /var/r1/field_sync/EOL_Data/RAF_Data/LRT/.
cp INSPYRE[rt]f??.kml /var/r1/field_sync/EOL_Data/RAF_Data/KML/.
cp INSPYRE?f??.iwg /var/r1/field_sync/EOL_Data/RAF_Data/IWG1/.
cp INSPYRE-CORE_GV_*RE*ict /var/r1/field_sync/EOL_Data/RAF_Data/ICARTT/.
cd /home/local/aircraft_QAtools_notebook
cp INSPYRE?f??.html /var/r1/field_sync/EOL_Data/RAF_Data/QA_Tools/.
cp INSPYRE?f??.pdf /var/r1/field_sync/EOL_Data/RAF_Data/QA_Tools/.
