#!/bin/csh

if ($uid == 20000) then
  cd /scr/raf/local_productiondata
else
  cd ${DATA_DIR}/IDEAS-4-C130
endif

foreach file ( IDEAS-4?f??.nc )
  echo $file
  ncReorder $file temp1.nc
  mv -f temp1.nc $file
  chmod g+w $file
end
