#!/bin/csh

set user = `whoami`
if ($user == 'nimbus') then
	cd /scr/raf/local_productiondata
else
	cd ${DATA_DIR}
endif

foreach file ( HIPPO-5?f??.nc )
  echo $file
  ncReorder $file temp2h5.nc
  mv -f temp2h5.nc $file
end
