#!/bin/sh

cd /etc

[ -f ntp.drift ] || echo "0.0" > ntp.drift

for d in rc0.d rc1.d rc6.d; do
    rm -f $d/K23ntpd
    [ -L $d/K77ntpd ] || ln -s ../init.d/ntpd $d/K77ntpd
done

for d in rc2.d; do
    [ -L $d/S21gps ] || ln -s ../init.d/ntpd $d/S21gps
    [ -L $d/S22ntpdate ] || ln -s ../init.d/ntpd $d/S22ntpdate
    [ -L $d/S23ntpd ] || ln -s ../init.d/ntpd $d/S23ntpd
done

# clean up old stuff installed during Cupido

# ntpd package installs this in /usr/bin
rm -f /usr/sbin/ntpq

# Now called just gps
rm -f init.d/gps_setclock
rm -f rc?.d/*gps_setclock

# libelf is a package, installs library in /usr/lib
rm -f /lib/libelf*
[ "$1" == "configure" ] && ldconfig

exit 0
