#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac :5 &
set xvpid=$!
sleep 2

setenv DISPLAY :5.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}
endif

setenv DAT ${DAT}/IDEAS-4-GV

mkdir ${DAT}

nice ./run_nimbus
nice ./reorder_all
nice ./run_proc2d

kill $xvpid
