#!/bin/csh

set busyFile='reorderInProgress'

cd ${DAT}

if (-f $busyFile) then
  exit 0
endif

touch $busyFile

foreach file ( SOCRATES*.nc )
  echo $file
  ncdump -h $file | head | grep --quiet UNLIMITED
  if ($status > 2) then
    nccopy -u $file temp.nc
    mv -f temp.nc $file
    chmod g+w $file
  endif
end

rm $busyFile
