#!/bin/csh

# Run FilterForWIC first
nice ./AddWIF HIPPO-5

# Then run terrain Ht
nice ./AddHtTerrain HIPPO-5 -65 85 -170 -80 no
# (Yes will download the terrain ht db. It takes forever. Change to no 
# after first run to speed things up.)

