# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

# Default ADS .login

export EDITOR=/usr/bin/vim
export PRINTER=raf-hp2300
export LESS=mCb50
export MORE=-c
export PAGER=less
export VISUAL=/usr/bin/vim

export RSYNC_RSH=ssh

export AEROS_CONFIG_DIR=$HOME/aeros_configs

# For nimbus ground transmission.
export XMIT_DIR=/tmp/xmit

#export PGDATA		/home/DataBases
export PGHOST=localhost
export PGUSER=ads
export PGDATABASE=real-time

# To prevent aeros track plot from crashing aeros.. 7/30/2010 cjw.
export COIN_FULL_INDIRECT_RENDERING=1
