#!/bin/bash

DISPLAY_NUM=9
if [ `whoami` == nimbus ]; then
  DISPLAY_NUM=8 #Set to 8 if running production to avoid overwriting.
fi

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :$DISPLAY_NUM &
xvpid=$!
trap "kill $xvpid; exit 1" SIGINT SIGTERM

sleep 2

DISPLAY=:${DISPLAY_NUM}.1

source ./set_env
source ${PROJ_DIR}/scripts/production_fns.sh
initialize_processing

./run_nimbus
reorder_all $PROJ
./run_proc2d

AddHtTerrain $PROJ # Set lat/lon box in AddHtTerrain, then uncomment here


if [ `whoami` == nimbus ]; then
#  run_kalmanFilter
  true
fi

cleanup_processing

kill $xvpid
exit 0
