#!/bin/sh

# chown root.root /root
# chmod 755 /root

chmod g-w /root

chmod 700 /root/.ssh

chmod 600 /root/.ssh/config

chmod 600 /root/.ssh/id_dsa

# Permissions are not as critical on these files,
# but we'll make them 600 anyway.
chmod 600 /root/.ssh/authorized_keys
chmod 600 /root/.ssh/id_dsa.pub

exit 0
