#!/bin/sh

exec > ./run_all_asc2cdf.log 2>&1

asc2cdf -m -d 2018-01-22 ${DAT}/RF03DatatoMergecopy.txt ${DAT}/RF03CVI20180122.nc
asc2cdf -m -d 2018-02-03 ${DAT}/RF08DatatoMergecopy.txt ${DAT}/RF08CVI20180203.nc
asc2cdf -m -d 2018-02-04 ${DAT}/RF09DatatoMergecopy.txt ${DAT}/RF09CVI20180204.nc
asc2cdf -m -d 2018-02-07 ${DAT}/RF10DatatoMergecopy.txt ${DAT}/RF10CVI20180207.nc
asc2cdf -m -d 2018-02-17 ${DAT}/RF12DatatoMergecopy.txt ${DAT}/RF12CVI20180217.nc
asc2cdf -m -d 2018-02-21 ${DAT}/RF14DatatoMergecopy.txt ${DAT}/RF14CVI20180221.nc
asc2cdf -m -d 2018-02-24 ${DAT}/RF15DatatoMergecopy.txt ${DAT}/RF15CVI20180224.nc
