#!/bin/sh

exec > ./run_all_asc2cdf.log 2>&1

asc2cdf -m -d 2018-01-22 ${CVIDAT}/RF03DatatoMergecopy.txt ${CVIDAT}/RF03CVI20180122.nc
asc2cdf -m -d 2018-02-03 ${CVIDAT}/RF08DatatoMergecopy.txt ${CVIDAT}/RF08CVI20180203.nc
asc2cdf -m -d 2018-02-04 ${CVIDAT}/RF09DatatoMergecopy.txt ${CVIDAT}/RF09CVI20180204.nc
asc2cdf -m -d 2018-02-07 ${CVIDAT}/RF10DatatoMergecopy.txt ${CVIDAT}/RF10CVI20180207.nc
asc2cdf -m -d 2018-02-17 ${CVIDAT}/RF12DatatoMergecopy.txt ${CVIDAT}/RF12CVI20180217.nc
asc2cdf -m -d 2018-02-21 ${CVIDAT}/RF14DatatoMergecopy.txt ${CVIDAT}/RF14CVI20180221.nc
asc2cdf -m -d 2018-02-24 ${CVIDAT}/RF15DatatoMergecopy.txt ${CVIDAT}/RF15CVI20180224.nc
