#!/bin/csh

process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210728_152701_rf03.2d -o ${DAT}/MethaneAIR21rf03.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210730_122056_rf04.2d -o ${DAT}/MethaneAIR21rf04.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210803_120340_rf35.2d -o ${DAT}/MethaneAIR21rf35.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210803_123910_rf05.2d -o ${DAT}/MethaneAIR21rf05.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210806_120529_rf06.2d -o ${DAT}/MethaneAIR21rf06.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210809_120601_rf07.2d -o ${DAT}/MethaneAIR21rf07.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210811_120857_rf08.2d -o ${DAT}/MethaneAIR21rf08.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210813_115616_rf09.2d -o ${DAT}/MethaneAIR21rf09.nc
process2d ${RAW_DATA_DIR}/MethaneAIR21/PMS2D/20210816_201801_rf10.2d -o ${DAT}/MethaneAIR21rf10.nc
