#!/bin/csh
set user = `whoami`
if ($user == 'nimbus') then
        cd /scr/raf/local_productiondata
else
        cd ${DATA_DIR}
endif

foreach FILENAME (HIPPO-4?f??.nc)
  echo $FILENAME
  ncReorder $FILENAME temp_h4.nc
  mv -f temp_h4.nc $FILENAME
end
