#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac :7 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :7.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/HIPPO
endif

mkdir ${DAT}

nice ./run_nimbus
nice ./reorder_all
nice ./run_proc2d
nice ./AddWIF HIPPO-2 ${DAT}
nice ./AddHtTerrain HIPPO-2 ${DAT} -67 85 172 -105 yes
# (Yes will download the terrain ht DB for the area of interest for this
# project. 
# It takes forever. Change to no after first run to speed things up.)
 nice ./rm_1DC HIPPO-2

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
