#! /bin/csh -f
#
#  Finish up archiving the movie files
#   RLR Tue Nov 27 23:20:20 GMT 2007
#
archcam.114 -a -f RF05 -p -t
archcam.114 -a -f RF06 -p -t
archcam.114 -a -f RF07 -p -t
archcam.114 -a -f RF08 -p -t
archcam.114 -a -f RF09 -p -t
archcam.114 -a -f RF10 -p -t
archcam.114 -a -f RF11 -p -t
archcam.114 -a -f RF12 -p -t
archcam.114 -a -f RF13 -p -t
archcam.114 -a -f RF14 -p -t
#
# Done.
exit
