#! /bin/csh -f
perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf01/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf02/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf03/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf04/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf05/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf06/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf07/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf08/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf09/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf10/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf11/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf12/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf13/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf14/forward/" "-s:60" "-t:5i"
#perl ./Image_Filter.pl "/scr/raf/Raw_Data/ACCLIP/camera_images/flight_number_rf15/forward/" "-s:60" "-t:5i"
