#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :7 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :7.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/HIPPO
endif

mkdir ${DAT}

nice ./run_nimbus
nice ./reorder_all
nice ../scripts/AddWIF HIPPO-1 ${DAT}
nice ../scripts/AddHtTerrain HIPPO-1 ${DAT} -70 90 165 -80 yes
# (Yes will download the terrain ht DB for the area of interest for this
# project. It takes forever. Change to no after first run to speed things up.)

# No 2D?
#nice ./run_proc2d

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
