#!/bin/bash

set -x

rm oap/*idx

cd TF01
extract2ds -project CAESAR -platform C130_N130AR -flight TF01 -sn HVPS315 -o ../oap/20240209_155210_tf01.2d base240*HVPS > output

cd ../TF02
extract2ds -project CAESAR -platform C130_N130AR -flight TF02 -sn HVPS315 -o ../oap/20240214_180602_tf02.2d base240*HVPS > output

cd ../TF03
extract2ds -project CAESAR -platform C130_N130AR -flight TF03 -sn HVPS315 -o ../oap/20240221_233035_tf03.2d base240*HVPS > output

cd ../TF04
extract2ds -project CAESAR -platform C130_N130AR -flight TF04 -sn HVPS315 -o ../oap/20240319_120123_tf04.2d base240*HVPS > output

cd ../TF05
extract2ds -project CAESAR -platform C130_N130AR -flight TF05 -sn HVPS315 -o ../oap/20240320_080628_tf05.2d base240*HVPS > output

cd ../TF06
extract2ds -project CAESAR -platform C130_N130AR -flight TF06 -sn HVPS315 -o ../oap/20240401_111340_tf06.2d base240*HVPS > output


cd ../RF01
extract2ds -project CAESAR -platform C130_N130AR -flight RF01 -sn HVPS315 -o ../oap/20240228_100632_rf01.2d base240*HVPS > output

cd ../RF02
extract2ds -project CAESAR -platform C130_N130AR -flight RF02 -sn HVPS315 -o ../oap/20240229_092712_rf02.2d base240*HVPS > output


cd ../RF04
extract2ds -project CAESAR -platform C130_N130AR -flight RF04 -sn HVPS315 -o ../oap/20240305_042712_rf04.2d base240*HVPS > output

cd ../RF05
extract2ds -project CAESAR -platform C130_N130AR -flight RF05 -sn HVPS315 -o ../oap/20240311_051816_rf05.2d base240*HVPS > output

cd ../RF06
extract2ds -project CAESAR -platform C130_N130AR -flight RF06 -sn HVPS315 -o ../oap/20240312_042101_rf06.2d base240*HVPS > output

cd ../RF07
extract2ds -project CAESAR -platform C130_N130AR -flight RF07 -sn HVPS315 -o ../oap/20240316_075701_rf07.2d base240*HVPS > output

#cd ../RF08
#extract2ds -project CAESAR -platform C130_N130AR -flight RF08 -sn HVPS315 -o ../oap/20240325_073329_rf08.2d base240*HVPS > output

cd ../RF09
extract2ds -project CAESAR -platform C130_N130AR -flight RF09 -sn HVPS315 -o ../oap/20240402_062603_rf09.2d base240*HVPS > output

cd ../RF10
extract2ds -project CAESAR -platform C130_N130AR -flight RF10 -sn HVPS315 -o ../oap/20240403_062236_rf10.2d base240*HVPS > output
