#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :7 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :7.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/ASPIRE-TEST
endif

mkdir ${DAT}

./run_nimbus
#./run_nimbus_hrt
./reorder_all
#nice ./AddHtTerrain  # Set lat/lon box in AddHtTerrain, then uncomment here
if ($uid == 20000) then
  #nice ./run_kalmanFilter  # Changes working dir, so run last.
endif

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
