#!/bin/bash

#/bin/netstat -I=ppp1 | tail -n 1
ifconfig ppp1|grep addr | sed 's/Mask:.*$//'

#in current Dell poweredge configuration eth3 is the satcom link
/bin/ping -I ppp1 -c 3 -W 15 -q www.ucar.edu
exit $?
