#!/bin/csh -f

if ($1 == '-H') then
  set process=$3
  set num = `ssh ads@$2 ps ax | grep $process | wc -l`
  exit $status
else
  set process=$1
  set num = `ps ax | grep $process | grep -v grep | grep -v check_proc | wc -l`
endif

if ($num > 1) then
 set plural="es"
else
 set plural=""
endif

if ($num == 0) then
 echo "CRITICAL: No processes!"
 exit 1
else
  echo "PROCS OK: $num process$plural found with command name $process"
  exit 0
endif
