#!/usr/bin/python

import select
import socket
import sys

HOST = ''
PORT = 7071

#struct timeval tv; tv.tv_sec = 5; t.tv_usec = 0;

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind((HOST, PORT))

r,w,e = select.select([s], [], [], 3)
if r:
	packet = r[0].recv(100)
	if (packet[0:3] == "IWG"):
		print "NIMBUS OK; ", packet
		s.close()
		sys.exit(0)
	else:
		print "NIMBUS WARNING; ", packet
		s.close()
		sys.exit(1)
else:
	print "NIMBUS CRITICAL; Did not recieve UDP packet on port %s after 3 seconds" % (PORT)
	s.close()
	sys.exit(2)


