#! /bin/sh

export CVI=/root/cvi

run_app() {
	echo -n "Starting cvi ..."
	$CVI/scripts/run_cvi.sh
	echo "."
}

kill_proc() {
    local proc=$1
    local sig="$2"
    ntry=0

    if [ -f /var/tmp/$proc.pid ]; then
        pid=$(</var/tmp/$prod.pid)
        while [ $ntry -lt 10 ]; do
            echo "kill $sig $pid"
            kill $sig $pid
            pids=(`ps -ef | fgrep $pid | fgrep -v fgrep | sed 's/  / /g' | cut -d \  -f 2`)
            [ ${#pids[*]} -eq 0 ] && return 0
            sleep 1
            ntry=$(($ntry + 1))
        done
    fi


    while [ $ntry -lt 10 ]; do
	pids=(`ps -ef | fgrep $proc | fgrep -v fgrep | sed 's/  / /g' | cut -d \  -f 2`)
	[ ${#pids[*]} -eq 0 ] && return 0
	echo "kill $sig ${pids[*]} ... "
	kill $sig ${pids[*]}
	sleep 1
	ntry=$(($ntry + 1))
    done
    return 1
}

kill_dsm() {
    kill_proc dsm -HUP || kill_proc dsm -9
}

case "$1" in
	start)
		run_app
  		;;
	stop)
		echo "Stopping dsm ... "
		if  kill_dsm; then
			echo "done"
		else
			echo "failed"
		fi
		echo -n "Unmounting $usbmtpt ... "
		if  umount_usb; then
			echo "done"
		else			
			echo "failed"
		fi
  		;;
	restart)
		echo "Stopping dsm ... "
		if  kill_dsm; then
			echo "done"
		else
			echo "failed"
		fi
		kill_dsm
  		sleep 5
  		run_app
  		;;
	*)
  		echo "Usage: /etc/init.d/cvi {start|stop|restart|copy|install}"
  		exit 1
		;;
esac

exit 0
