#!/bin/csh

foreach FILENAME (setup_rf??)
  nimbus -b $FILENAME
end

#cd /jnet/productiondata/
cd /jnet/data/
foreach FILENAME (HIPPOrf??.nc)
  ncReorder $FILENAME temp.nc
  /bin/mv -f temp.nc $FILENAME
end

