#!/bin/sh
#

Rscript -e "library(knitr); knitr::purl('/h/eol/janine/Rstudio/HeightOfTerrain/HeightOfTerrain.Rnw')"

project="WECAN"
lt_s="48"
lt_n="35"
lg_w="-125"
lg_e="-109"
Tdb="yes"
# Set Tdb to yes the first time this is run to download the Terrain database. Set to no after
# to save time.

echo "Adding Terrain Ht vars to production netCDF files for project $project"
echo "Using lat/long range $lt_s - $lt_n, $lg_w - $lg_e"

for file in `ls /scr/raf/Prod_Data/${project}/${project}[rtf]f??.nc`
do
    flight=${file:(-7):4}
    Rscript ./HeightOfTerrain.R $project $flight $lt_s $lt_n $lg_w $lg_e $Tdb
done
