#!/bin/csh


# Remove existing files.  Helps to avoid residual data if nimbus fails.
/bin/rm ${DAT}/SPICULE?f??.nc

sleep 3

foreach setup_file ( setup_?f?? )
  nimbus -b $setup_file

# Use this for old recovery factor processing:
# I think this is now committed.....
#  /scr/raf/cjw/nimbus/src/filter/nimbus -b $setup_file
end
