#!/bin/bash

source ./set_env

if [ -d ${RAW_DATA_DIR}/${PROJ}/F2DS/oap ]; then

  for file in ${RAW_DATA_DIR}/${PROJ}/F2DS/oap/*2d
  do
    bfname=`basename $file`
    flight=`echo $bfname | cut -b 17-20`
    process2d ${RAW_DATA_DIR}/${PROJ}/F2DS/oap/${bfname} -o ${DAT}/${PROJ}${flight}.nc
  done
fi

