#!/bin/sh

# script for controlling digital output pins
# on a viper (/dev/viper_dio0).
# Intended for bench testing.

dev=/dev/viper_dio0

if [ $# -eq 0 ]; then
    echo "usage: $0 p d p d p d ..."
    echo "where p is a output pin number (0-7) and d is a 0 or 1"
    exit 1
fi

ck_dout $dev $*

