#!/bin/csh

set user = `whoami`
if ($user == 'nimbus') then
        cd /scr/raf/local_productiondata
else
        cd ${DATA_DIR}
endif

foreach file ( TORERO?f??.nc )
  echo $file
  ncReorder $file temp_torero.nc
  mv -f temp_torero.nc $file
  chmod g+w $file
end
