#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :5 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :5.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/TORERO
endif

mkdir ${DAT}

nice ./run_nimbus
nice ./reorder_all
nice ./run_proc2d
nice ../scripts/AddWIF TORERO ${DAT}
nice ../scripts/AddHtTerrain TORERO ${DAT} -40 10 -105 -70 no
# (Yes will download the terrain ht DB for the area of interest for this
# project. It takes forever. Change to no after first run to speed things
# up.)

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
