#!/bin/csh

set display=":9"

Xvfb -screen 0 1600x1200x24 -pn -ac $display &

setenv DISPLAY localhost${display}.0 

/bin/cp -f ${PROJ_DIR}/VOCALS/C130_N130AR/SegmentA/* ${PROJ_DIR}/VOCALS/C130_N130AR

foreach FILENAME (`ls setup_rf0[1-4]`)
  nimbus -b $FILENAME
EOF
end

/bin/cp -f ${PROJ_DIR}/VOCALS/C130_N130AR/SegmentB/* ${PROJ_DIR}/VOCALS/C130_N130AR
foreach FILENAME (`ls setup_rf0[5-9]`)
  nimbus -b $FILENAME
EOF
end

/bin/cp -f ${PROJ_DIR}/VOCALS/C130_N130AR/SegmentC/* ${PROJ_DIR}/VOCALS/C130_N130AR
foreach FILENAME (`ls setup_rf0[5-9]`)
  nimbus -b $FILENAME
EOF
end

pkill Xvfb

cd /jnet/productiondata/
rm voc_temp.nc
foreach FILENAME (VOCAL*.nc)
ncReorder $FILENAME voc_temp.nc
if (-e voc_temp.nc) then
  mv -f voc_temp.nc $FILENAME
endif
end
