#!/bin/csh

ncfixdate ${PROD_DATA}/PACDEXrf10.nc <<EOL
05/17/2007
EOL

ncfixdate ${PROD_DATA}/PACDEXrf10h.nc <<EOP
05/17/2007
EOP

ncfixdate ${PROD_DATA}/PACDEXrf12.nc <<EON
05/22/2007
EON

ncfixdate ${PROD_DATA}/PACDEXrf12h.nc <<EOT
05/22/2007
EOT
