#!/bin/csh

ncfixdate ${DAT}/PACDEXrf10.nc <<EOL
05/17/2007
EOL

ncfixdate ${DAT}/PACDEXrf10h.nc <<EOP
05/17/2007
EOP

ncfixdate ${DAT}/PACDEXrf12.nc <<EON
05/22/2007
EON

ncfixdate ${DAT}/PACDEXrf12h.nc <<EOT
05/22/2007
EOT
