#!/bin/csh

ncfixdate /jnet/productiondata/PACDEXrf10.nc <<EOL
05/17/2007
EOL

ncfixdate /jnet/productiondata/PACDEXrf10h.nc <<EOP
05/17/2007
EOP

ncfixdate /jnet/productiondata/PACDEXrf12.nc <<EON
05/22/2007
EON

ncfixdate /jnet/productiondata/PACDEXrf12h.nc <<EOT
05/22/2007
EOT
