#!/bin/csh

set display=":9"

Xvfb -screen 0 1600x1200x24 -pn -ac $display &

setenv DISPLAY localhost${display}.0 

/bin/cp LRT/setup* .
/bin/cp LRT/Lags ../.
foreach FILENAME (`ls setup_rf*`)
nimbus -b $FILENAME
end

#/bin/cp HRT/setup* .
#/bin/cp HRT/Lags ../.
#foreach FILENAME (`ls setup_rf*`)
#nimbus -b $FILENAME
#end

pkill Xvfb

# Restore low rate lags as default.
/bin/rm setup*
/bin/cp LRT/Lags ../.

cd ${PROD_DATA}
rm pac_temp.nc
foreach FILENAME (PACDEX*.nc)
ncReorder $FILENAME pac_temp.nc
if (-e pac_temp.nc) then
  /bin/mv -f pac_temp.nc $FILENAME
endif
end

ncfixdate ${PROD_DATA}/PACDEXrf10.nc <<EOL
05/17/2007
EOL
ncatted -a units,Time,m,c,"seconds since 2007-05-17 01:20:00 +0000" ${PROD_DATA}/PACDEXrf10.nc

ncfixdate ${PROD_DATA}/PACDEXrf10h.nc <<EOP
05/17/2007
EOP

ncfixdate ${PROD_DATA}/PACDEXrf12.nc <<EON
05/22/2007
EON
ncatted -a units,Time,m,c,"seconds since 2007-05-22 00:27:25 +0000" ${PROD_DATA}/PACDEXrf12.nc

ncfixdate ${PROD_DATA}/PACDEXrf12h.nc <<EOT
05/22/2007
EOT
