#!/bin/csh

nimbus -b setup_rf01
nimbus -b setup_rf02
nimbus -b setup_rf03
nimbus -b setup_rf04
nimbus -b setup_rf05
nimbus -b setup_rf06
nimbus -b setup_rf07
nimbus -b setup_rf08
nimbus -b setup_rf09
nimbus -b setup_rf10
nimbus -b setup_rf11
nimbus -b setup_rf12
