#!/bin/csh

foreach FILENAME (`ls setup_rf*`)
nimbus -b $FILENAME << EOF
Y
EOF
end

cd /jnet/productiondata/
rm pac_temp.nc
foreach FILENAME (PACDEX*.nc)
ncReorder $FILENAME pac_temp.nc
if (-e pac_temp.nc) then
  mv -f pac_temp.nc $FILENAME
endif
end

#ncfixdate /jnet/productiondata/PACDEXrf10.nc <<EOL
#05/17/2007
#EOL

ncfixdate /jnet/productiondata/PACDEXrf10h.nc <<EOP
05/17/2007
EOP

#ncfixdate /jnet/productiondata/PACDEXrf12.nc <<EON
#05/22/2007
#EON

ncfixdate /jnet/productiondata/PACDEXrf12h.nc <<EOT
05/22/2007
EOT

