#!/bin/csh

cd ${RAW_DATA_DIR}/ARISTO2016/2DS

foreach file ([RF]*/*2DS)
    set flight=`echo $file | sed 's/\/.*$//'`
    translate2ds -flight $flight -project ARISTO2016 -platform C130_N130AR -sn SPEC001 -f $file
    set outfile=`echo $file | sed 's/.2DS/.2d/'`
    set twodfile=`echo $outfile | sed 's/^.*\///'`
    mv $twodfile $outfile
end


cd ${RAW_DATA_DIR}/ARISTO2016/3VCPI

foreach file ([RF]*/*2DSCPI)
    set flight=`echo $file | sed 's/\/.*$//'`
    translate2ds -flight $flight -project ARISTO2016 -platform C130_N130AR -sn SPEC001 -f $file
    set outfile=`echo $file | sed 's/.2DSCPI/.2d/'`
    set twodfile=`echo $outfile | sed 's/^.*\///'`
    mv $twodfile $outfile
end

