#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <PROJECT>"
  exit 1
fi

PROJ=$(echo "$1" | tr '[:lower:]' '[:upper:]')

if [ `whoami` == nimbus ]; then
  DAT=/scr/raf/local_productiondata/
else
  DAT=${DATA_DIR}/${PROJ}
fi
##Activate the conda environment needed for HeightOfTerrain. This is installed on all EOL servers (merc/saturnt)
source /opt/local/anaconda3/etc/profile.d/conda.sh
conda activate qatools_env

# Set Tdb to yes the first time this is run to download the Terrain database.
# It will check and skip downloading if it already exists.
Tdb="yes"

echo "Adding Terrain Ht vars to netCDF files in ${DAT} for project ${PROJ}"

for file in ${DAT}/${PROJ}[rtf]f??.nc; do
    flight=$(basename ${file} | grep -oP '[rtf]f\d{2}')
    echo "HeightOfTerrain ${PROJ} ${flight} ${DAT}"
    # Uncomment the following line to actually run the script
    HeightOfTerrain ${PROJ} ${flight} ${DAT}
done