#!/bin/csh

echo "This script is intended to create final processing scripts and nimbus setup"
echo "files for batch processing.  Current incarnation does research and ferry"
echo "flights.  Scripts will most likely need tweaking to get exact results, but"
echo "this provides a useful first pass."
echo
echo "Make sure all the ads files you want are downloaded, and unwanted ads files have"
echo "been removed (e.g. superfluous ground ads files).  Also make sure extract2d has"
echo "been run and the all the desired 2d files are in place.  Be sure to merge 2d"
echo "files if multiple files exist for one flight."
echo
echo "Usage:"
echo "cd SOCRATES/GV_N677F/Production"
echo "init_processing SOCRATES"
echo
echo "Edit run_proc2d to add/remove 2d processing lines."
echo
echo -n "Proceed (y/N) ? "
set proceed = $<

if ($proceed != "y") then
  exit(1)
endif

if ($#argv == 0) then
  echo "Usage:\n init_processing proj_name\n"

  echo 'Prerequisites: ads files have been copied into RAW_DATA_DIR/proj_name and extract2d has been run (i.e. all .2d files exist in $RAW_DATA_DIR/$proj/PMS2D/)'
  exit
endif

set proj=$argv[1]
set dat=${DATA_DIR}/${proj}


# ---------------------------------------------------------
# set_env script
#
cat > set_env << EOFSE
#!/bin/bash

PROJ=$proj

AIRCRAFT=\$(n_hdr_util \${RAW_DATA_DIR}/\${PROJ}/*.ads | grep 'system name:' | awk '{print \$3}')

if [ \`whoami\` == nimbus ]; then
  DAT=/scr/raf/local_productiondata/
else
  DAT=\${DATA_DIR}/\${PROJ}
fi
EOFSE


# ---------------------------------------------------------
# run_all script
#
cat > run_all << "EOFRA"
#!/bin/bash

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :9 &
xvpid=$!
trap "kill $xvpid; exit 1" SIGINT SIGTERM
sleep 2

DISPLAY=:9.1

source ./set_env
source ${PROJ_DIR}/scripts/production_fns.sh
initialize_processing

./run_nimbus
source ${PROJ_DIR}/scripts/reorder_all $PROJ
./run_proc2d

# AddHtTerrain  # Set lat/lon box in AddHtTerrain, then uncomment here

if [ `whoami` == nimbus ]; then
#  run_kalmanFilter
  true
fi

cleanup_processing

kill $xvpid
exit 0
"EOFRA"


# ---------------------------------------------------------
# run_nimbus script.
#
cat > run_nimbus << "EOFRN"
#!/bin/bash

source ./set_env

# Remove existing files.  Helps to avoid residual data if nimbus fails.
/bin/rm ${DAT}/${PROJ}?f??.nc

for setup_file in setup_?f??
do
  nimbus -b $setup_file
done
"EOFRN"


# ---------------------------------------------------------
# nimbus setup_* files.
#
foreach file (${RAW_DATA_DIR}/$proj/*[rft]f*.ads)
  set bfname=`basename $file`
  set flight=`echo $bfname | cut -b 17-20`
  echo 'if=${RAW_DATA_DIR}/'$proj'/'$bfname > setup_$flight
  echo 'of=${DATA_DIR}/'${proj}'/'${proj}${flight}.nc >> setup_$flight
end


# ---------------------------------------------------------
# Fast 2D processing script.
#
cat > run_proc2d << "EOF2D"
#!/bin/bash

source ./set_env

if [ -d ${RAW_DATA_DIR}/${PROJ}/PMS2D ]; then

  for file in ${RAW_DATA_DIR}/${PROJ}/PMS2D/*2d
  do
    bfname=`basename $file`
    flight=`echo $bfname | cut -b 17-20`
    process2d ${RAW_DATA_DIR}/${PROJ}/PMS2D/${bfname} -o ${DAT}/${PROJ}${flight}.nc
  done
fi

if [ -d ${RAW_DATA_DIR}/${PROJ}/F2DS/oap ]; then

  for file in ${RAW_DATA_DIR}/${PROJ}/F2DS/oap/*2d
  do
    bfname=`basename $file`
    flight=`echo $bfname | cut -b 17-20`
    process2d ${RAW_DATA_DIR}/${PROJ}/F2DS/oap/${bfname} -o ${DAT}/${PROJ}${flight}.nc
  done
fi

if [ -d ${RAW_DATA_DIR}/${PROJ}/HVPS/oap ]; then

  for file in ${RAW_DATA_DIR}/${PROJ}/HVPS/oap/*2d
  do
    bfname=`basename $file`
    flight=`echo $bfname | cut -b 17-20`
    process2d ${RAW_DATA_DIR}/${PROJ}/HVPS/oap/${bfname} -o ${DAT}/${PROJ}${flight}.nc
  done
fi

"EOF2D"


chmod +x set_env run_all run_nimbus run_proc2d
chmod g+w set_env run_all run_nimbus run_proc2d setup_*
