#!/bin/bash

# Load EPEL repos.
rpm -ivh http://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -ihv http://www.eol.ucar.edu/software/rpms/eol-repo-epel-1-3.noarch.rpm

yum install group "Development Tools"

# @TODO Ask lab vs. GV vs. C130.

yum install raf-ads3-lab

yum install "nidas*"
yum install "cmigit*"

