#!/bin/bash
#
# Launches nimbus for real-time aircraft mode.

#
# SMS text that aircraft is up.
#
# Until outbound mail from acserver is re-enabled, comment this out.
# echo "$AIRCRAFT Datasystem is up" | mail -s "$AIRCRAFT is Online" 3038832241@txt.att.net

# Make sure it exists.
/bin/mkdir -p $XMIT_DIR

# Remove AVAPS DropSonde files.
/bin/rm -f /mnt/r1/send_to_grnd/D20*
/bin/rm -f /tmp/avaps-rt
/bin/rm /var/www/html/skewt/D*svg

# Fire up nimbus in real-time with transmit on.
# gnome-terminal --title NIMBUS -- nimbus -rt3 -x 3
gnome-terminal --title NIMBUS -- bash -c "nimbus -rt3 -x 3 --log tag=rtloop3,debug 2>> /tmp/nimbus_$(date +%Y%m%d).log"
