#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <PROJECT>"
  exit 1
fi

PROJ=$(echo "$1" | tr '[:lower:]' '[:upper:]')

busyFile='reorderInProgress'
trap "rm $busyFile" SIGINT SIGTERM

if [ `whoami` == nimbus ]; then
  DAT=/scr/raf/local_productiondata/
else
  DAT=${DATA_DIR}/${PROJ}
fi
cd ${DAT}

if [ -f $busyFile ]; then
  exit 1
fi

touch $busyFile

for file in ${PROJ}?f??.nc
do
  echo $file
  ncdump -h $file | head | grep --quiet UNLIMITED
  if [ $? -eq 0 ]; then
    nccopy -u $file reotemp.nc
    mv -f reotemp.nc $file
    chmod g+w $file
  fi
done

/bin/rm $busyFile
