#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <PROJECT>"
  exit 1
fi

PROJ=$(echo "$1" | tr '[:lower:]' '[:upper:]')
AIRCRAFT=$(n_hdr_util ${RAW_DATA_DIR}/${PROJ}/*.ads | grep 'system name:' | awk '{print $3}')

busyFile='reorderInProgress'
trap "rm $busyFile" SIGINT SIGTERM

source ./set_env

cd ${DAT}

if [ -f $busyFile ]; then
  exit 1
fi

touch $busyFile

for file in ${PROJ}?f??.nc
do
  echo $file
  ncdump -h $file | head | grep --quiet UNLIMITED
  if [ $? -eq 0 ]; then
    nccopy -u $file reotemp.nc
    mv -f reotemp.nc $file
    chmod g+w $file
  fi
done

/bin/rm $busyFile
