#!/bin/bash

# Script to update all existing subvserion & git repositories in current directory.

for repo in *; do

  if [ -d "${repo}/.svn" ]; then
    echo "<<<<  $repo  >>>>"
    svn status $repo
  fi

  if [ -d "${repo}/.git" ]; then
    echo "<<<<  $repo  >>>>"
    cd $repo
    git --no-pager branch
    git status -s
    cd ..
  fi
done

