#!/bin/bash

logger "start_cameras shell script called"

# Reset symlink script so it gets new flight number.
# Let ensure_running start it back up.
pkill camera_symlink

/etc/init.d/capture.sh stop
pkill VimbaC

# [Re]load firewire drivers.
sudo modprobe -r firewire_ohci
sudo modprobe firewire_ohci

# (Re)set camera images symlink for camera web page display
touch /var/www/html/camera
cd /var/www/html/camera
rm camera_images
cam_path=`get_ac_config.py cameras.path`
ln -s `dirname ${cam_path}`

sleep 2

/etc/init.d/capture.sh start 

sleep 2

mkdir -p  $cam_path/down
cd $cam_path/down

/opt/local/Vimba_5_1/VimbaC/Examples/SynchronousGrab/Build/Make/binary/x86_64bit/SynchronousGrab &
