#!/bin/bash

logger "start_cameras shell script called"

# Reset symlink script so it gets new flight number.
# Let ensure_running start it back up.
pkill camera_symlink

/etc/init.d/capture.sh stop
#/bin/capture stop
pkill VimbaC
# Vimba related tool
pkill exiftool


#restart ethernet camera before getting to firewire drivers
cam_path=`get_ac_config.py cameras.path`
mkdir -p  $cam_path/down
cd $cam_path/down
rm /tmp/VimbaCam.log
if ! ps h -C Vimba | grep -v "[Vimba]" > /dev/null
then
    /opt/local/Vimba_5_1/VimbaC/Examples/SynchronousGrab/Build/Make/binary/x86_64bit/SynchronousGrab >/tmp/VimbaCam.log &
else
    echo "Vimba already running, not restarting"
fi

# [Re]load firewire drivers.
sudo modprobe -r firewire_ohci
sudo modprobe firewire_ohci

# (Re)set camera images symlink for camera web page display
touch /var/www/html/camera
cd /var/www/html/camera
rm camera_images
cam_path=`get_ac_config.py cameras.path`
ln -s `dirname ${cam_path}`

sleep 2

/etc/init.d/capture.sh start

sleep 800000

