#!/bin/csh

set busyFile='reorderInProgress'

cd ${DAT}

if (-f $busyFile) then
  exit 0
endif

touch $busyFile

foreach file ( WECANrf??.nc )
  ncdump -h $file | head | grep --quiet UNLIMITED
  if ($status > 2) then
    echo $file " Processing"
    nccopy -u $file reotemp.nc
    mv -f reotemp.nc $file
    chmod g+w $file
  else
    echo $file " Didn't need re-ordering"
  endif
end

rm $busyFile
