#!/bin/csh

# Remove existing files.  Helps to avoid if a residual data if nimbus fails.
/bin/rm ${DAT}/WECAN?f??.nc

foreach setup_file ( setup_?f?? )
  nimbus -b $setup_file
end

echo "Don't forget to merge 2DS data files (WECAN?f??2DS.nc) with new LRT files."
echo "To do this, run  run_process2ds."
