#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac :5 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :5.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/WECAN
endif

mkdir ${DAT}

#nice ./run_nimbus
#nice ./reorder_all
#nice ./run_proc2d
#./run_nimbus
./reorder_all
./run_proc2d
#../scripts/icartt.sh
echo "***After run_all, don't forget to merge MR_UVH and CVI vars***"
echo "***Scripts for merging are in proj WECAN***"
kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
