#!/bin/bash

busyFile='reorderInProgress'
trap "rm $busyFile" SIGINT SIGTERM

source ./set_env

cd ${DAT}

if [ -f $busyFile ]; then
  exit 1
fi

touch $busyFile

for file in ${PROJ}?f??.nc
do
  echo $file
  ncdump -h $file | head | grep --quiet UNLIMITED
  if [ $? -eq 0 ]; then
    nccopy -u $file reotemp.nc
    mv -f reotemp.nc $file
    chmod g+w $file
  fi
done

/bin/rm $busyFile
