#!/bin/bash

source ./set_env

filelist=setup_?f??

# For CAESAR, RF08 was aborted.  Ferry flights 1,2,5,and 6 enter Canada
# which we do not have permission to distribute the data.
if [ `whoami` == nimbus ]; then
  filelist='setup_rf0[1-7,9] setup_rf10 setup_tf?? setup_ff0[34]'
fi

# Remove existing files.  Helps to avoid residual data if nimbus fails.
/bin/rm ${DAT}/${PROJ}?f??.nc

for setup_file in $filelist
do
  nimbus -b $setup_file
done
