#!/bin/bash

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :9 &
xvpid=$!
trap "kill $xvpid; exit 1" SIGINT SIGTERM
sleep 2

DISPLAY=:9.1

source ./set_env

mkdir -p ${DAT}
if [ `whoami` == nimbus ]; then
    git clone https://github.com/NCAR/aircraft_projects.git /scr/raf/temp/aircraft_projects
    export PROJ_DIR="/scr/raf/temp/aircraft_projects"
    cd $PROJ_DIR/CAESAR/C130_N130AR/Production
fi

./run_nimbus
./reorder_all
./run_proc2d

#./AddHtTerrain  # Set lat/lon box in AddHtTerrain, then uncomment here

if [ `whoami` == nimbus ]; then
    export PROJ_DIR="/net/jlocal/projects"
    cd $PROJ_DIR
    rm -rf /scr/raf/temp/aircraft_projects
    # ./run_kalmanFilter  # Changes working dir, so run last.
fi

kill $xvpid
exit 0
