#!/bin/bash

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :6 &
xvpid=$!
trap "kill $xvpid; exit 1" SIGINT SIGTERM
sleep 2

DISPLAY=:6.1

source ./set_env
source ${PROJ_DIR}/scripts/production_fns.sh
initialize_processing
./run_nimbus_hrt
./reorder_all

cleanup_processing

kill $xvpid
exit 0
