#!/bin/csh -x

# Adapt on a per project basis.

pkill radar.NEXRAD

cd /var/www/html/flight_data/images

# Age-off; 720 minutes is 12 hours, 1440 is 24 hours.
find . -name "ops*.jpg" -mmin +360 -exec rm {} \;

# Greg Stossmeister puts the latest filename into the aircraft database
# and sends a NOTIFY.  listen_sat.pl on the aircraft hears it, and calls
# this script.

# Get filename from database, and then retrieve file.
set sql_cmd="SELECT filename FROM satellite WHERE product = 'rad_comp';"
set name=`psql -h eol-rt-data.guest.ucar.edu -d $PGGRND -q -t -c "$sql_cmd"`
wget --limit-rate=4000 ftp://catalog.eol.ucar.edu/pub/incoming/plows/radar/$name -O $name.tmp

if (-s ${name}.tmp) then
  /bin/mv ${name}.tmp $name
  /bin/cp $name latest_radar.jpg
else
  rm ${name}.tmp
endif
