#!/bin/csh

# Adapt on a per project basis.

pkill ch1_vis
pkill ch4_thermal

cd /var/www/html/flight_data/images

# Age-off; 720 minutes is 12 hours, 1440 is 24 hours.
find . -name "ops*.jpg" -mmin +360 -exec rm {} \;

# Greg Stossmeister puts the latest filename into the aircraft database
# and sends a NOTIFY.  listen_sat.pl on the aircraft hears it, and calls
# this script.

# Get filename from database, and then retrieve file.
set sql_cmd="SELECT filename FROM satellite WHERE product = 'sat_$argv[1]';"
set name=`psql -h eol-rt-data.guest.ucar.edu -d $PGGRND -q -t -c "$sql_cmd"`
wget --limit-rate=3000 ftp://data.eol.ucar.edu/pub/incoming/predict/mc_sat/$name -O $name.tmp

if (-s ${name}.tmp) then
  /bin/mv ${name}.tmp $name
  /bin/cp $name latest_$1.jpg
else
  rm ${name}.tmp
endif

exit

# Previous method.
rm tmp.jpg
wget --limit-rate=4000 http://www.eol.ucar.edu/~cjw/misc/c130_vis.jpg -O tmp.jpg
/bin/mv tmp.jpg `date +%y%m%d-%H%M%S`_vis-c130.jpg

wget --limit-rate=4000 http://www.eol.ucar.edu/~cjw/misc/c130_ir.jpg -O tmp.jpg
/bin/mv tmp.jpg `date +%y%m%d-%H%M%S`_ir-c130.jpg
