#!/bin/csh

# Adapt on a per project basis.

cd /var/www/html/images

# Sounding, Proj=ADELE, Melbourne Florida
wget -q -r --limit-rate=4000 http://www.rap.ucar.edu/weather/upper/jax.gif -O jax.gif

# No update for Melbourne since July 11.
#wget -q -r --limit-rate=4000 http://www.rap.ucar.edu/weather/upper/xmr.gif -O xmr.gif
