#!/bin/bash
#
# Launches nimbus for real-time aircraft mode.

#echo "sending texts to Chris and Tom"
#
# SMS text Chris that aircraft is up.
#echo "$AIRCRAFT Datasystem is up" | mail -s "$AIRCRAFT is Online" 3038832241@txt.att.net

#echo "setting up vcsel specturm stash"
#
#  Temporarily stash the VCSEL spectrum to /tmp/vcsel.spec.txt
#pkill data_dump
#rm /tmp/vcsel.spec.txt
#data_dump -i 4,330 | grep SPEC > /tmp/vcsel.spec.txt &


# Make sure it exists.
/bin/mkdir -p $XMIT_DIR

# Remove AVAPS DropSonde files.
/bin/rm -f /mnt/r1/send_to_grnd/D20*
/bin/rm -f /tmp/avaps-rt
/bin/rm /var/www/html/skewt/D*svg

# Fire up nimbus in real-time with transmit on.
gnome-terminal --title NIMBUS -x nimbus -rt3 -x 5
