#!/bin/csh
#
# Launches nimbus for real-time aircraft mode.

setenv XMIT_DIR /tmp/xmit

# Make sure it exists.
/bin/mkdir -p $XMIT_DIR

# Remove AVAPS DropSonde files.
/bin/rm -f /mnt/r2/send_to_grnd/D20*
/bin/rm -f /tmp/avaps-rt

(setenv PGDATABASE $PGGRND; /home/local/Systems/scripts/listen_sat.pl) &


# Start google map/earth updater onboard.
pkill acTrack2kml
acTrack2kml -o &

# Fire up nimbus in real-time with transmit on.
nimbus -rt3 -x

# remove google updater.
pkill acTrack2kml
