#!/bin/csh
#
# Launches nimbus for real-time aircraft mode.

# Make sure it exists.
/bin/mkdir -p $XMIT_DIR

# Remove AVAPS DropSonde files.
/bin/rm -f /mnt/r2/send_to_grnd/D20*
/bin/rm -f /tmp/avaps-rt

# Fire up nimbus in real-time with transmit on.
nimbus -rt3 -x
