#!/bin/sh

# Bring to known state, remove any residual ppp or ddclient stuff
#sudo pkill ppp
#sudo pkill ddclient

#ifdown eth2

# Reset eth3.  ifdown bgan does not seem to fully kill the connection.
ifdown eth3
sleep 3
ifup eth3

# sudo /usr/sbin/adsl-start

# New way to start pppoe.  Uses options in
# /etc/sysconfig/network-scripts/ifcfg-ppp0

ifup bgan
 
gnome-terminal --title "INMARSAT Log" -x /home/local/Systems/scripts/show_mpds_log.csh
