#!/bin/bash

# Start of a script for installing/updating software on an aircraft server.

cd /home/local

dir=raf
if [ ! -d $dir ]; then
  svn co http://svn.eol.ucar.edu/svn/raf/trunk $dir
else
  svn update $dir
fi

dir=Systems
if [ ! -d $dir ]; then
  svn co http://svn.eol.ucar.edu/svn/raf/Systems
else
  svn update $dir
fi

dir=projects
if [ ! -d $dir ]; then
  svn co --non-recursive http://svn.eol.ucar.edu/svn/projects
  svn update projects/Configuration
  svn update projects/RAF_Lab
else
  svn update $dir
fi

dir=nidas
if [ ! -d $dir ]; then
  # We need --recursive for nidas for the ARINC driver.
  git clone --recursive https://github.com/ncareol/$dir
else
  cd $dir
  git pull origin master
  cd ..
fi

# CMIGITS Code.  ITAR controlled.
# git clone file:///net/cds/git/cmigits-nidas.git
# cd cmigits-nidas/
# Onboard build >>>>  make BUILDS='armbe'

dir=libraf
if [ ! -d $dir ]; then
  git clone https://github.com/ncar/$dir
else
  cd $dir
  git pull origin master
  cd ..
fi

dir=ncplot
if [ ! -d $dir ]; then
  git clone https://github.com/ncareol/$dir
else
  cd $dir
  git pull origin master
  cd ..
fi

dir=aeros
if [ ! -d $dir ]; then
  # We need --recursive for aeros to get eol_scons.
  git clone --recursive https://github.com/ncareol/$dir
else
  cd $dir
  git pull origin master
  git submodule update --init
  cd ..
fi

dir=ric
if [ ! -d $dir ]; then
  # We need --recursive for aeros to get eol_scons.
  git clone --recursive https://github.com/ncareol/$dir
else
  cd $dir
  git pull origin master
  git submodule update --init
  cd ..
fi

