#!/bin/csh -f

# Age-off; 1440 is 24 hours, 360 is 6 hours, 600 is 10 hours.

find /var/www/html/flight_data/images -name "satellite*.jpg*" -mmin +720 -exec rm {} \;
find /var/www/html/flight_data/images -name "radar*.gif*" -mmin +720 -exec rm {} \;
find /var/www/html/flight_data/images -name "NEXRAD*.png*" -mmin +720 -exec rm {} \;
find /var/www/html/flight_data/images -name "research*.png" -mmin +720 -exec rm {} \;
find /var/www/html/flight_data/images -name "latest*" -mmin +720 -exec rm {} \;
find /var/www/html/flight_data/GE -name last_hour_lightning.kml -mmin +30 -exec rm {} \;
find /var/www/html/flight_data/GE -name "*_Flight_Plan.kml" -mmin +720 -exec rm {} \;
find /var/www/html/skewt -name "*.svg" -mmin +1440 -exec rm {} \;
find /tmp/avaps-rt -name "D*" -mmin +720 -exec rm {} \;
find /tmp -maxdepth 1 -name "iostat*" -mmin +3000 -exec rm{} \;
#find /tmp -name "get_sat_*.log" -mmin +1440 -exec rm {} \;

# Don't allow the lock files to remain too long.
find /mnt/r1/dropsondes -name "BUSY" -mmin +20 -exec rm {} \;
find /var/www/html/flight_data/images/ -name "*BUSY*" -mmin +10 -exec rm {} \;
find /var/www/html/flight_data/GE/ -name "*BUSY*" -mmin +5 -exec rm {} \;

# Clean these every couple months.
find /mnt/r1/dropsondes -name "D*" -mmin +80000 -exec rm {} \;
find /mnt/r1/mtp -name "MTPcurrent*.txt" -mmin +80000 -exec rm -f {} \;
find /mnt/r1/mtp -name "ATP_*.txt" -mmin +80000 -exec rm -f {} \;
find /mnt/r1/toga -name "*.b" -mmin +800 -exec rm -f {} \;
