#!/bin/csh -f

# Age-off; 1440 is 24 hours, 360 is 6 hours, 600 is 10 hours.

find /var/www/html/flight_data/images -name "ops*.jpg" -mmin +720 -exec rm {} \;
find /var/www/html/skewt -name "*.svg" -mmin +1440 -exec rm {} \;

# Don't allow the lock file to remain too long.
find /mnt/r1/dropsondes -name "BUSY" -mmin +20 -exec rm {} \;

# Clean these every couple months.
find /mnt/r1/dropsondes -name "D*" -mmin +80000 -exec rm {} \;
find /mnt/r1/mtp -name "MTPcurrent*.txt" -mmin +80000 -exec rm -f {} \;
