#!/bin/bash
#
#  This script will recreate the database on the ground
#    so that inserts sent from the plane will be successful
#    Takes an argument that is a zipped file of SQL commands
#    usually found in the directory /tmp/xmit
#
#    Called by Nimbus
#

cd /tmp/xmit

export PGHOST="eol-rt-data.guest.ucar.edu"
#echo $PGHOST

export PGDATABASE="real-time-"`gunzip -c $1 | head -n1`
#echo $PGDATABASE

gunzip -c $1 | psql
