#!/bin/csh
#
#  This script will recreate the database on the ground
#    so that inserts sent from the plane will be successful
#    Takes an argument that is a zipped file of SQL commands
#    usually found in the directory /tmp/xmit
#
#    Called by Nimbus
#

cd /tmp/xmit

gunzip $1
set filename=`basename $1 .gz`

sed 1,1d $filename | psql -h eol-rt-data.guest.ucar.edu -d $PGGRND
