#!/bin/csh -x

logger "start_cameras shell script called"

/etc/init.d/capture.sh stop

sudo modprobe -r firewire_ohci
sudo modprobe firewire_ohci

# Reset camera images symlink for camera web page display
cd /var/www/html/camera
rm camera_images
set cam_path=`get_ac_config.py cameras.path`
ln -s `dirname ${cam_path}`

sleep 2

/etc/init.d/capture.sh start &
