#!/bin/csh
#######
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff01
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff02
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff03
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff04
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff05
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff06
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff07
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff08
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff09
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile ff10
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf01
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf02
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf03
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf04
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf05
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf06
nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf07
nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf08
nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf09
nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf10
nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf11
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf12
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf13
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf14
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile rf15
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile tf01
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl SOCRATES.paramfile tf02
