#!/bin/csh
#####
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_ff01/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_ff02/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_ff03/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf01/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf02/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf03/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf04/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf05/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf06/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf07/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf08/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf09/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf10/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf11/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf13/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf14/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf15/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf16/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf17/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf18/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_rf19/forward/" "-proj:SOCRATES" "-s:15" "-Y"
/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_tf01/forward/" "-proj:SOCRATES" "-s:15" "-Y"
#/net/work/bin/converters/ImageFilter/Image_Filter.pl "/scr/raf/Raw_Data/SOCRATES/camera_images/flight_number_tf02/forward/" "-proj:SOCRATES" "-s:15" "-Y"

