#!/bin/csh

cd ${RAW_DATA_DIR}/SOCRATES/2DS

foreach file ([RTF]*/*)
    set flight=`echo $file | sed 's/\/.*$//'`
    translate2ds -flight $flight -project SOCRATES -platform GV_N677F -sn SPEC001 -f $file
    set outfile=`echo $file | sed 's/.2DS/.2d/'`
    set twodfile=`echo $outfile | sed 's/^.*\///'`
    mv $twodfile $outfile
end

