# This script merges the Kalman filtered HRT variables from the .hKF files
# into the high rate C130_*nc files that Chris created for Sam.

ncmerge -v LATKF,LONKF,ALTKF,VEWKF,VNSKF,ROCKF,PITCHKF,ROLLKF,THDGKF,WDKF,WSKF,WIKF,WICC,WDCC,WSCC,UXKF,VYKF,AKKF,SSKF C130_20201111_tf01.nc WCR-TESTtf01hKF.nc
ncmerge -v LATKF,LONKF,ALTKF,VEWKF,VNSKF,ROCKF,PITCHKF,ROLLKF,THDGKF,WDKF,WSKF,WIKF,WICC,WDCC,WSCC,UXKF,VYKF,AKKF,SSKF C130_20201120_tf02.nc WCR-TESTtf02hKF.nc
