#!/usr/bin/python
###########################################################
# Before each project, set the project name here, then copy
# the script to /opt/local/bin
###########################################################
import os
os.environ['PROJECT'] = 'SPICULE'
os.system('/net/jlocal/projects/scripts/push_data.py')
