#!/bin/bash

source ${PROJ_DIR}/INSPYRE/GV_N677F/Production/set_env

# BEFORE RUNNING THIS SCRIPT, MANUALLY UPDATE /opt/local/bin/nc2asc as
# appropriate for new version and set version indicator letter here:
version="E"

# Remove existing files.  Helps to avoid residual data if nc2asc fails
/bin/rm ${DAT}/${PROJ}-CORE_GV_????????_R${version}*.nc

for file in ${DAT}/${PROJ}?f??.nc
do
  takeoff=`flt_time ${file} | sed -n 's/^Takeoff: //p'`
  ymd=`date -d "$takeoff" +%Y%m%d`
  outfile="${DAT}/${PROJ}-CORE_GV_${ymd}_R${version}.nc"
  if [[ -f "$outfile" ]]; then
    # If recreating an existing file, assume have two legs.
    # Code does NOT handle more than two legs ATM.
    base=${outfile%.nc}
    mv $outfile ${base}_L1.nc
    cp $file ${base}_L2.nc
  else
    cp $file $outfile
  fi
done
