#!/bin/csh

# Remove existing files.  Helps to avoid if a residual data if nimbus fails.
#/bin/rm ${DAT}/PREDICT?f??.nc

foreach setup_file ( setup_?f?? )
# Using this nimbus to avoid the dual element recovery factor.
  /scr/raf/cjw/nimbus/src/filter/nimbus -b $setup_file
end
