#!/bin/csh
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf01
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf02
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf03
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf04
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf05
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf06
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf07
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf08
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf09
nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf10
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf11
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf12
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf13
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf14
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf15
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf16
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf17
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf18
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf19
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf20
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf21
#nice +19 /net/work/bin/converters/createMovies/combineCameras.pl OTREC.paramfile rf22
