#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac :2 &
set xvpid=$!
onintr int
sleep 2
  
setenv DISPLAY :2.1
  
if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/DC3
endif

mkdir ${DAT}

nice ./run_nimbus_hrt
nice ./reorder_all
#nice ./run_proc2d
#nice ../scripts/AddWIF DC3 ${DAT}
#nice ../scripts/AddHtTerrain DC3 ${DAT} 24 43 -106 -85 yes
# (Yes will download the terrain ht DB for the area of interest for this
# project. It takes forever. Change to no after first run to speed things
# up.)

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
