#!/bin/bash -eux

#
# initialize an acserver for IrcBot
#

#
# prerequisites:
# - installation of raf-catalog package >= 1.0-3
# - GitHub deploy key copied to ~catalog/.ssh/ircbot_deploy_key_rsa
#

if [ `whoami` != 'catalog' ]; then
  echo "ERROR: $0 must be run as 'catalog' user"
  exit 1
fi

if [ ! -f ~/.ssh/ircbot_deploy_key_rsa ]; then
  echo "ERROR: SSH key ~/.ssh/ircbot_deploy_key_rsa does not exist. Please add SSH key."
  exit 1
fi

if [ -z "$CATALOG_PLANE" ]; then
  echo "ERROR: CATALOG_PLANE must be set."
  exit 1
fi

\cd

git clone ssh://github-irc-bot/ncareol/irc-bot.git

touch db.sqlite3

\cd irc-bot

git checkout master

ln -sv docker/docker-compose.yml docker-compose.yml

\cd config

#
# bot config: link plane-specific config to config/irc-bot.yml
#
ln -sv "$CATALOG_PLANE"bot.yml irc-bot.yml

#
# check config: link plane-specific config to config/rectify-bot.yml
#
ln -sv "$CATALOG_PLANE"-check-bot.yml rectify-bot.yml

\cd ..

docker-compose pull
docker-compose build

docker-compose run app bundle --path vendor --local

sudo systemctl start irc-bot
