#!/bin/csh

/usr/bin/Xvfb -screen 1 1280x1024x16 -pn -ac -nolisten tcp :8 &
set xvpid=$!
onintr int
sleep 2

setenv DISPLAY :8.1

if ($uid == 20000) then
  setenv DAT /scr/raf/local_productiondata/
else
  setenv DAT ${DATA_DIR}/CONTRAST
endif

mkdir ${DAT}

nice ./run_nimbus
#nice ./run_nimbus_hrt
# Based on feedback from aerosol and cloud probe scientists Mike Reeves and Sarah Woods
# remove USHAS and CDP vars from high rate processing. Use ncks instead of Flight_ files per Chris Webster
# ex ncks -a -x -v ACDP_RWOO,CCDP_RWOO,AUHSAS_RWOI,CUHSAS_RWOI CONTRAST####h.nc CONTRAST####h.nc

nice ./reorder_all
nice ./run_proc2d

kill $xvpid
exit 0

int:
  kill $xvpid
  exit 1
